name: Flight Booking CICD

on:
  push:
    branches:
      - dev
      - main

jobs:
  upload-to-dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Validate Variables JSON
        run: |
          test -f variables/dev/variables.json || echo "Missing variables.json file for dev"

      - name: Upload Variables JSON to GCS
        run: |
          set -e
          gsutil cp variables/dev/variables.json gs://australia-southeast2-keyvan-b133332f-bucket/data/dev/variables.json

      - name: Import Variables into Airflow-DEV
        run: |
          gcloud composer environments run keyvan-dev \
            --location australia-southeast2 \
            variables import -- gs://australia-southeast2-keyvan-b133332f-bucket/data/dev/variables.json

      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark-job.py gs://keyvan/spark-job/

      - name: Upload Airflow DAG to DEV
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-dev \
            --location australia-southeast2 \
            --source airflow_job.py

  upload-to-prod:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Validate Variables JSON
        run: |
          test -f variables/prod/variables.json || echo "Missing variables.json file for prod"

      - name: Upload Variables JSON to GCS
        run: |
          set -e
          gsutil cp variables/prod/variables.json gs://australia-southeast2-keyvan-c891ca7e-bucket/data/prod/variables.json

      - name: Import Variables into Airflow-PROD
        run: |
          gcloud composer environments run keyvan-prod \
            --location australia-southeast2 \
            variables import -- gs://australia-southeast2-keyvan-c891ca7e-bucket/data/prod/variables.json

      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark-job.py gs://keyvan/spark-job/

      - name: Upload Airflow DAG to PROD
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-prod \
            --location australia-southeast2 \
            --source airflow_job.py
